### ISSUE TITLE
Possibly add a license to this repo

### ISSUE THREAD

**Issue by mlinksva** [petergoes/open-letter-regarding-article-13#3]
Might be over the top, but might also be worth just to communicate to other developers they have legalistic permission to reuse the text, beyond the encouragement you've put in the README. :smile:

Here's a shortcut link to choose CC0-1.0 ie no restrictions but of course you could choose something else: https://github.com/petergoes/open-letter-regarding-article-13/community/license/new?branch=master&template=cc0-1.0

**Comment by petergoes** [comment]
Done
